name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
      full-test:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v7
            with:
              clean: false
              submodules: 'recursive'
            env:
              # This forces Git to accept the parent repository and all submodules as safe,
              # overriding the temporary HOME sandbox behavior.
              GIT_CONFIG_COUNT: 2
              GIT_CONFIG_KEY_0: safe.directory
              GIT_CONFIG_VALUE_0: '${{ github.workspace }}'
              GIT_CONFIG_KEY_1: safe.directory
              GIT_CONFIG_VALUE_1: '${{ github.workspace }}/*'
          - name: Run build
            timeout-minutes: 600
            run: |
               docker run --rm \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:26-assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./build.sh
