name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
      full-test:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v7
            with:
              clean: false
              submodules: 'recursive'
          - name: Run build
            timeout-minutes: 600
            run: |
               docker run --rm \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:26-assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./build.sh
